[pytest]
pythonpath = src
testpaths = tests
addopts =
    -v
    --cov=src
    --cov-report=html:doc/htmlcov
    --cov-report=term-missing

console_output_style = progress

[coverage:run]
source = src
omit =
    */tests/*
    */test_*.py
    */__pycache__/*

[coverage:report]
exclude_lines =
    pragma: no cover
    def __repr__
    raise AssertionError
    raise NotImplementedError
    if __name__ == .__main__.:
    if TYPE_CHECKING:
    @abstractmethod

[coverage:html]
directory = doc/htmlcov